version: '3.4'

services:
  master:
    build:
      context: .
      target: jenkins-master
    image: brentlaster/dc_jenkins:1.5 

  agent:
    build:
      context: .
      target: jenkins-agent
    image: brentlaster/jenkins-agent
