# Centralized Jenkins CI stack example with dynamic build agents (assumed that master has Jenkins Swarm Plugin installed)
version: '3.3'

services:
  agent:
    image: brentlaster/jenkins-agent
    environment:
      - "MASTER_HOST=master"
      - "MASTER_JNLP_PORT=50000"
      - "MASTER_HTTP_PORT=8080"
    deploy:
      mode: global
      # placement:
      #   constraints:
      #     - node.labels.jenkins == agent
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G
      restart_policy:
        condition: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - agent-workspace:/var/jenkins_workspace
    networks:
      - jenkins


volumes:
  master:
  agent-workspace:

networks:
  jenkins:
